# Generated by Django 3.1.2 on 2021-04-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210406_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.blog'),
        ),
    ]
